keys:
  # Personal key (for editing secrets)
  - &henhal-lenovo age13azyggpzlzzsp3levku6ecjaqd3cq3eapeu9e6nnrzp6eguk6cwscsted0
  - &henhal-workstation age1jqsvyav7pplf7m9k9lk59andsazs984493hrcuxp2nrg2vd59u6segy47m

  # Machine keys (SSH host key → age, for decryption at boot)
  - &lenovo age1sxv8q8hlyc8lhy3ydzexds93rl8pdql944hm4y2df56pq4qssujskg3k9q
  - &workstation age1qrxkpmvytq3cfrka4nkl2sn79nyg2r7t8qm55m0rl7vrlqc7v3zqadq2yj
  - &hp-server age1w05f4s0uqatmctt2vpz786722ux4y30fe89lsw3rzz7xtkuxa9tqefmyzw

  # TODO: Add workstation and hp-server keys
  # - &workstation age1...
  # - &hp-server age1...

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env)$
    key_groups:
      - age:
        - *henhal-lenovo
        - *henhal-workstation
        - *lenovo
        - *workstation
        - *hp-server
