{pkgs, ...}: let
  # Gmail PWA launcher — opens Chrome in app mode targeting Gmail
  # WM class will be "mail.google.com" (used for Hyprland window rules)
  gmail = pkgs.writeShellScriptBin "gmail" ''
    exec ${pkgs.google-chrome}/bin/google-chrome-stable \
      --app=https://mail.google.com \
      --no-default-browser-check \
      --force-dark-mode \
      --enable-features=WebContentsForceDark \
      --no-first-run
  '';

  # Toggle Gmail special workspace — launches Gmail if not running, then shows/hides
  toggleGmail = pkgs.writeShellScriptBin "toggle-gmail" ''
    CLASS="chrome-mail.google.com__-Default"
    GMAIL_PROCESS_PATTERN='google-chrome.*--app=https://mail.google.com'

    if [ -n "''${NIRI_SOCKET-}" ] || [ "''${XDG_CURRENT_DESKTOP-}" = "niri" ]; then
      if ! pgrep -fa "$GMAIL_PROCESS_PATTERN" >/dev/null; then
        gmail &
        sleep 0.5
      fi

      niri msg action focus-workspace gmail
      exit 0
    fi

    # Launch Gmail if no window exists yet
    if ! hyprctl clients | grep -q "class: $CLASS"; then
      gmail &
      # Wait up to 5s for the window to appear in the special workspace
      for i in $(seq 1 10); do
        sleep 0.5
        hyprctl clients | grep -q "class: $CLASS" && break
      done
    fi

    hyprctl dispatch togglespecialworkspace gmail
  '';
in {
  # 1. Install Google Chrome + helpers
  home.packages = [pkgs.google-chrome gmail toggleGmail];

  # 2. Override the default .desktop file to add the --incognito flag
  xdg.desktopEntries."google-chrome-incognito" = {
    # Using a slightly different name avoids potential conflicts and makes it clear
    name = "Google Chrome (Incognito)";
    comment = "Access the internet (Incognito Mode)";
    # Use the executable provided by the Nix package and add the flag
    # Assuming 'google-chrome-stable' is the executable name in the package's bin dir
    exec = "${pkgs.google-chrome}/bin/google-chrome-stable --incognito %U";
    # Use the standard Chrome icon
    icon = "google-chrome";
    terminal = false;
    type = "Application";
    # Common categories for a web browser
    categories = ["Network" "WebBrowser"];
    # You might need to copy MimeType= line from the original .desktop file if needed
    # MimeType = "text/html;...";
  };

  # Optional: Remove the original non-incognito entry if you ONLY want the incognito one
  # Be cautious with this, as it might affect other system integrations.
  # xdg.desktopEntries."google-chrome".visible = false; # Hides original entry
  # Or fully remove it (might require finding the exact name generated by the package)
  # xdg.desktopEntries."google-chrome".name = lib.mkForce null;
}
