return {}
-- return {
--   {
--     'yetone/avante.nvim',
--     event = 'VeryLazy',
--     lazy = false,
--     version = false, -- set this if you want to always pull the latest change
--     --[[     config = function()
--       require('avante_lib').load()
--       require('avante').setup {}
--     end,
--  ]]
--     keys = {
--
--       { '<leader>aa', '<cmd>AvanteAsk<cr>', mode = { 'n', 'v' }, desc = 'Avante Ask' },
--       { '<leader>ae', '<cmd>AvanteEdit<cr>', mode = { 'n', 'v' }, desc = 'Avante Edit' },
--     },
--     opts = {
--       provider = 'claude', -- Recommend using Claude
--       auto_suggestions_provider = 'claude', -- Since auto-suggestions are a high-frequency operation and therefore expensive, it is recommended to specify an inexpensive provider or even a free provider: copilot
--       claude = {
--         endpoint = 'https://api.anthropic.com',
--         model = 'claude-3-5-sonnet-20240620',
--         temperature = 0,
--         max_tokens = 4096,
--       },
--       debug = true,
--       behaviour = {
--         auto_suggestions = false, -- Experimental stage
--         auto_set_highlight_group = true,
--         auto_set_keymaps = false,
--         auto_apply_diff_after_generation = false,
--         support_paste_from_clipboard = false,
--       },
--       mappings = {
--         diff = {
--           ours = 'co',
--           theirs = 'ct',
--           all_theirs = 'ca',
--           both = 'cb',
--           cursor = 'cc',
--           next = ']x',
--           prev = '[x',
--         },
--         suggestion = {
--           accept = '<M-l>',
--           next = '<M-]>',
--           prev = '<M-[>',
--           dismiss = '<C-]>',
--         },
--         jump = {
--           next = ']]',
--           prev = '[[',
--         },
--         submit = {
--           normal = '<CR>',
--           insert = '<C-s>',
--         },
--         sidebar = {
--           switch_windows = '<Tab>',
--           reverse_switch_windows = '<S-Tab>',
--         },
--       },
--       hints = { enabled = true },
--       windows = {
--         position = 'right',
--         wrap = true,
--         width = 30,
--         sidebar_header = {
--           align = 'center',
--           rounded = true,
--         },
--       },
--       highlights = {
--         diff = {
--           current = 'DiffText',
--           incoming = 'DiffAdd',
--         },
--       },
--       diff = {
--         autojump = true,
--         list_opener = 'copen',
--       },
--     },
--     build = 'make',
--     -- build = "powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false", -- for windows
--     dependencies = {
--       'stevearc/dressing.nvim',
--       'nvim-lua/plenary.nvim',
--       'MunifTanjim/nui.nvim',
--       'nvim-tree/nvim-web-devicons',
--       'zbirenbaum/copilot.lua',
--       {
--         'HakonHarnes/img-clip.nvim',
--         event = 'VeryLazy',
--         opts = {
--           default = {
--             embed_image_as_base64 = false,
--             prompt_for_file_name = false,
--             drag_and_drop = {
--               insert_mode = true,
--             },
--             use_absolute_path = true,
--           },
--         },
--       },
--       {
--         'MeanderingProgrammer/render-markdown.nvim',
--         opts = {
--           file_types = { 'markdown', 'Avante' },
--         },
--         ft = { 'markdown', 'Avante' },
--       },
--     },
--   },
-- }
